name: get_garmin_activity_counts

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        
      - uses: nanasess/setup-chromedriver@master
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Test chromedriver
        env: # Or as an environment variable
          super_secret: ${{ secrets.SuperSecret }}
        run: python test_chromedriver.py
        
      - name: Commit and push if it changed
        run: |-
         git config user.name "Automated"
         git config user.email "actions@users.noreply.github.com"
         echo "Test" > test.txt
         git add test.txt
         timestamp=$(date -u)
         git commit -m "Latest data: ${timestamp}" || exit 0
         git push
